from django.urls import path

from .room_media_access import MemberRoomMediaView
from .views import (
    AddRoomMemberView,
    CreateRoomView,
    DirectMessageView,
    JoinRoomView,
    LeaveRoomView,
    MarkRoomReadView,
    MessageDeleteView,
    MessageEditView,
    MessageForwardView,
    RemoveRoomMemberView,
    SendMediaMessageView,
    UpdateRoomView,
    chat_page,
    first_chat,
)

urlpatterns = [
    path(
        "start/",
        first_chat,
        name="first_chat",
    ),
    path(
        "rooms/create/",
        CreateRoomView.as_view(),
        name="create_room",
    ),
    path(
        "rooms/<int:room_id>/join/",
        JoinRoomView.as_view(),
        name="join_room",
    ),
    path(
        "rooms/<int:room_id>/update/",
        UpdateRoomView.as_view(),
        name="update_room",
    ),
    path(
        "rooms/<int:room_id>/members/",
        AddRoomMemberView.as_view(),
        name="add_room_member",
    ),
    path(
        "rooms/<int:room_id>/members/<int:user_id>/remove/",
        RemoveRoomMemberView.as_view(),
        name="remove_room_member",
    ),
    path(
        "rooms/<int:room_id>/leave/",
        LeaveRoomView.as_view(),
        name="leave_room",
    ),
    path(
        "rooms/<int:room_id>/send_file/",
        SendMediaMessageView.as_view(),
        name="send_message_file",
    ),
    path(
        "rooms/<int:room_id>/media/",
        MemberRoomMediaView.as_view(),
        name="room_media",
    ),
    path(
        "rooms/<int:room_id>/read/",
        MarkRoomReadView.as_view(),
        name="room_read",
    ),
    path(
        "messages/<int:message_id>/edit/",
        MessageEditView.as_view(),
        name="edit_message",
    ),
    path(
        "messages/<int:message_id>/delete/",
        MessageDeleteView.as_view(),
        name="delete_message",
    ),
    path(
        "messages/<int:message_id>/forward/",
        MessageForwardView.as_view(),
        name="forward_message",
    ),
    path(
        "direct/",
        DirectMessageView.as_view(),
        name="direct_message",
    ),
    path(
        "<str:room_name>/",
        chat_page,
        name="chat",
    ),
]
